services:
  user_manager_db:
    image: postgres:13
    restart: always
    user: ${DB_USER}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 2s
      timeout: 1s
      retries: 5
    ports:
      - "$DB_PORT:$DB_PORT"
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME

  user_manager:
    build: ./user_manager
    ports:
      - "$USER_MANAGER_PORT:$USER_MANAGER_PORT"
    depends_on:
      user_manager_db:
        condition: service_healthy
    environment:
      - DB_HOST=user_manager_db
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_NAME=$DB_NAME
      - PORT=$USER_MANAGER_PORT
      - JWT_USER_SECRET=$USER_MANAGER_JWT_USER_SECRET
      - JWT_INTERNAL_SECRET=$USER_MANAGER_JWT_INTERNAL_SECRET

volumes:
  db_data:

