services:
  user_manager_db:
    image: postgres:13
    restart: always
    user: ${DB_USER}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 2s
      timeout: 1s
      retries: 5
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME

  user_manager_transfer_db:
    image: neo4j:4.2
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/$NEO4J_PASS
    volumes:
      - /var/lib/neo4j/data:/data
      - /var/lib/neo4j/logs:/logs
      - /var/lib/neo4j/config:/config
      - /var/lib/neo4j/plugins:/plugins

  gateway:
    build: ./gateway
    ports:
      - "$GATEWAY_PORT:$GATEWAY_PORT"
    depends_on:
      - user_manager
      - game_lobby
    environment:
      - FLASK_RUN_PORT=$GATEWAY_PORT
      - FLASK_RUN_HOST=0.0.0.0
      - USER_MANAGER_HOST=user_manager
      - USER_MANAGER_PORT=$USER_MANAGER_PORT
      - GAME_LOBBY_HOST=game_lobby
      - GAME_LOBBY_PORT=$GAME_LOBBY_PORT

  user_manager:
    build: ./user_manager
    depends_on:
      user_manager_db:
        condition: service_healthy
    environment:
      - DB_HOST=user_manager_db
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_NAME=$DB_NAME
      - NEO4J_BOLT_PORT=$NEO4J_BOLT_PORT
      - NEO4J_BROWSER_PORT=$NEO4J_BROWSER_PORT
      - NEO4J_USER=$NEO4J_USER
      - NEO4J_PASS=$NEO4J_PASS
      - NEO4J_HOST=user_manager_transfer_db
      - NEO4J_DATABASE=$NEO4J_DATABASE
      - PORT=$USER_MANAGER_PORT
      - JWT_USER_SECRET=$USER_MANAGER_JWT_USER_SECRET
      - JWT_INTERNAL_SECRET=$JWT_INTERNAL_SECRET
      - EXCHANGE_SERVICE_HOST=exchange-service
      - EXCHANGE_SERVICE_PORT=$EXCHANGE_SERVICE_PORT

  game_lobby:
    build: ./game_lobby
    # depends_on:
    #   user_manager:
    #     condition: service_healthy
    environment:
      - USER_MANAGER_HOST=user_manager
      - USER_MANAGER_PORT=$USER_MANAGER_PORT
      - GAME_LOBBY_PORT=$GAME_LOBBY_PORT
      - JWT_INTERNAL_SECRET=$JWT_INTERNAL_SECRET
      - JWT_USER_SECRET=$USER_MANAGER_JWT_USER_SECRET
      - EXCHANGE_SERVICE_HOST=exchange-service
      - EXCHANGE_SERVICE_PORT=$EXCHANGE_SERVICE_PORT

  exchange-service:
    build: ./exchange-service
    environment:
      - PORT=$EXCHANGE_SERVICE_PORT

volumes:
  db_data:
